### ISSUE TITLE
[BUG] <unable to get local issuer certificate>

### ISSUE THREAD

**Issue by Kannannagaraj** [npm/minipass-fetch#3]
request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to get local issuer certificate
FetchError: request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\node_modules\minipass-fetch\lib\index.js:97:14)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:215:7)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

tried all below 

npm config set registry http://registry.npmjs.org/
npm config set strict-ssl false
NODE_TLS_REJECT_UNAUTHORIZED =0

**Comment by isaacs** [comment]
This looks more like an npm issue than a minipass-fetch issue.  Do you have a `proxy` config?
